language: python
sudo: true
python:
    - "3.8"

services:
    - docker

before_script:
    - pip install docker-compose

install:
    - pip install -U pip
    - pip install -U pytest
  
script:
    - docker-compose run app sh -c "pytest test.py -p no:cacheprovider"

deploy:
    provider: script
    skip-cleanup: true
    script: bash travis/deploy.sh
    on:
        branch: cloud_development