language: python
sudo: true
python:
    - "3.8"

services:
    - docker

before_install:
    - pip install -U pip
    - pip install -U pytest

install:
  - pip install ".[test]" . # install package + test dependencies
  
script:
    - pytest # run tests

deploy:
    provider: script
    skip-cleanup: true
    script: bash travis/deploy.sh
    on:
        branch: cloud_development